// The "en" section of this file is automatically generated. Do not modify it.
// Other translations (e.g., "ru", "zh-cn", "zh-tw") can be modified manually.
// However, running automation scripts will delete non-"en" translations.
// Make sure to back up any manual changes before running scripts.
/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
/* eslint-disable quotes */
/* eslint-disable quote-props */
/* eslint-disable dot-notation */
/* eslint-disable max-len */
function getInterfaceTranslations () {
    return {
        "en": {
            "openai.name": "OpenAI",
            "openai.description": "Allows users to chat with OpenAI, enabling interactive and intelligent conversations."
        },
        "ru": {
            "openai.name": "OpenAI",
            "openai.description": "Позволяет пользователям общаться с OpenAI, обеспечивая интерактивные и интеллектуальные беседы."
        },
        "zh-cn": {
            "openai.name": "OpenAI",
            "openai.description": "允许用户与OpenAI聊天，实现互动和智能对话。"
        },
        "zh-tw": {
            "openai.name": "OpenAI",
            "openai.description": "允許用戶與OpenAI聊天，實現互動和智能對話。"
        }
    };
}

function registerScratchExtensionTranslations () {
    return {
        "en": {
            "openai.temperature.veryConservative": "Very Conservative",
            "openai.temperature.conservative": "Conservative",
            "openai.temperature.balanced": "Balanced",
            "openai.temperature.creative": "Creative",
            "openai.temperature.veryCreative": "Very Creative",
            "openai.categoryName": "OpenAI",
            "openai.setApiKey": "set OpenAI API Key to [API_KEY]",
            "openai.askOpenAI": "ask OpenAI [PROMPT]",
            "openai.askOpenAI.default": "Hello, OpenAI!",
            "openai.tellOpenAI": "Set the pre-instruction for OpenAI [CONTENT]",
            "openai.tellOpenAI.default": "You are a cute devil bird.",
            "openai.clearHistory": "clear conversation history",
            "openai.chooseModel": "set AI model to [MODEL]",
            "openai.setTemperature": "set response style to [STYLE]",
            "openai.missingApiKey": "Oops! It seems like you forgot to set the API Key. Please make sure it\"s set before asking OpenAI.",
            "openai.invalidResponse": "Something went wrong. OpenAI didn\"t respond as expected. Please try again.",
            "openai.connectionError": "Something went wrong with the connection. Please check your internet and API key, and try again.",
            "openai.networkError": "There seems to be a network issue. Please check your connection and try again."
        },
        "ru": {
            "openai.temperature.veryConservative": "Очень консервативно",
            "openai.temperature.conservative": "Консервативно",
            "openai.temperature.balanced": "Сбалансировано",
            "openai.temperature.creative": "Креативно",
            "openai.temperature.veryCreative": "Очень креативно",
            "openai.categoryName": "OpenAI",
            "openai.setApiKey": "Установить API-ключ OpenAI на [API_KEY]",
            "openai.askOpenAI": "спросить OpenAI [PROMPT]",
            "openai.askOpenAI.default": "Привет, OpenAI!",
            "openai.tellOpenAI": "Установить предустановку для OpenAI [CONTENT]",
            "openai.tellOpenAI.default": "Ты милая птичка-дьявол.",
            "openai.clearHistory": "очистить историю разговоров",
            "openai.chooseModel": "установить модель ИИ на [MODEL]",
            "openai.setTemperature": "установить стиль ответа на [STYLE]",
            "openai.missingApiKey": "Упс! Кажется, вы забыли установить API-ключ. Пожалуйста, убедитесь, что он установлен, прежде чем спрашивать OpenAI.",
            "openai.invalidResponse": "Что-то пошло не так. OpenAI не ответил, как ожидалось. Пожалуйста, попробуйте еще раз.",
            "openai.connectionError": "Что-то пошло не так с подключением. Пожалуйста, проверьте ваш интернет и API-ключ, и попробуйте снова.",
            "openai.networkError": "Похоже, возникла проблема с сетью. Пожалуйста, проверьте ваше соединение и попробуйте снова."
        },
        "zh-cn": {
            "openai.temperature.veryConservative": "非常保守",
            "openai.temperature.conservative": "保守",
            "openai.temperature.balanced": "平衡",
            "openai.temperature.creative": "创意",
            "openai.temperature.veryCreative": "非常创意",
            "openai.categoryName": "OpenAI",
            "openai.setApiKey": "设置 OpenAI API 密钥为 [API_KEY]",
            "openai.askOpenAI": "向 OpenAI 提问 [PROMPT]",
            "openai.askOpenAI.default": "你好，OpenAI！",
            "openai.tellOpenAI": "设置 OpenAI 的预设指令 [CONTENT]",
            "openai.tellOpenAI.default": "你是一只可爱的恶魔鸟。",
            "openai.clearHistory": "清除对话历史",
            "openai.chooseModel": "设置 AI 模型为 [MODEL]",
            "openai.setTemperature": "设置响应风格为 [STYLE]",
            "openai.missingApiKey": "哎呀！似乎您忘记设置 API 密钥了。请在向 OpenAI 提问前确保已设置。",
            "openai.invalidResponse": "出错了。OpenAI 没有按预期响应。请再试一次。",
            "openai.connectionError": "连接出错了。请检查您的网络和 API 密钥，然后重试。",
            "openai.networkError": "似乎出现了网络问题。请检查您的连接并重试。"
        },
        "zh-tw": {
            "openai.temperature.veryConservative": "非常保守",
            "openai.temperature.conservative": "保守",
            "openai.temperature.balanced": "平衡",
            "openai.temperature.creative": "創意",
            "openai.temperature.veryCreative": "非常創意",
            "openai.categoryName": "OpenAI",
            "openai.setApiKey": "設置 OpenAI API 密鑰為 [API_KEY]",
            "openai.askOpenAI": "向 OpenAI 提問 [PROMPT]",
            "openai.askOpenAI.default": "你好，OpenAI！",
            "openai.tellOpenAI": "設置 OpenAI 的預設指令 [CONTENT]",
            "openai.tellOpenAI.default": "你是一隻可愛的惡魔鳥。",
            "openai.clearHistory": "清除對話歷史",
            "openai.chooseModel": "設置 AI 模型為 [MODEL]",
            "openai.setTemperature": "設置響應風格為 [STYLE]",
            "openai.missingApiKey": "哎呀！似乎您忘記設置 API 密鑰了。請在向 OpenAI 提問前確保已設置。",
            "openai.invalidResponse": "出錯了。OpenAI 沒有按預期響應。請再試一次。",
            "openai.connectionError": "連接出錯了。請檢查您的網絡和 API 密鑰，然後重試。",
            "openai.networkError": "似乎出現了網路問題。請檢查您的連線並重試。"
        }
    };
}

function registerBlocksMessages (Blockly) {
    return Blockly;
}

if (typeof module !== 'undefined') {
    module.exports = {getInterfaceTranslations};
}
exports = registerScratchExtensionTranslations;
exports = registerBlocksMessages;
